approvedGitRepositories:
    - "https://npm-registry.sipwise.com/*"

enableScripts: true

npmMinimalAgeGate: 0

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://npm-registry.sipwise.com/"
