#!/bin/bash

if ! [ -f /.dockerenv ] && ! grep -q 'devices:/docker' /proc/1/cgroup ; then
  echo "Not running inside docker, exiting to avoid data damage." >&2
  exit 1
fi

set -e
set -u

echo "Checking CSC address configuration"
application_to_test="$1"
ui_address="$2"
api_address="$3"
if [ -z "${ui_address}" ] ; then
  echo "ERROR: Missing UI address, please check the script parameters. Aborting."
  exit 1
fi
echo "Found UI address '${ui_address}', processing further..."

config_file="cypress.ci.${application_to_test}.config.js"
sed -i -e "s|\"baseUrl\":.*|\"baseUrl\": \"${ui_address}\",|" "${config_file}"
sed -i -e "s|\"apiHost\":.*|\"apiHost\": \"${api_address}\",|" "${config_file}"

task_name="ci:${application_to_test}"
yarnpkg run "${task_name}" --browser chrome
